use_pd_ctrl: false
use_joint_name: true
num_of_actuation_joint: 19
joints_name: ["waist_yaw_joint", "waist_roll_joint", "waist_pitch_joint",
              "head_yaw_joint", "head_pitch_joint",
              "left_shoulder_pitch_joint", "left_shoulder_roll_joint", "left_shoulder_yaw_joint", "left_elbow_joint", 
              "left_wrist_yaw_joint", "left_wrist_pitch_joint", "left_hand_yaw_joint",
              "right_shoulder_pitch_joint", "right_shoulder_roll_joint", "right_shoulder_yaw_joint", "right_elbow_joint", 
              "right_wrist_yaw_joint", "right_wrist_pitch_joint", "right_hand_yaw_joint"]